SELECT
    a.object_id,
    right_ascension,
    declination,
    tile_index,
    det_quality_flag,
    flux_vis_unif,
    phz_mode_1,
    phz_median,
    phz_flags,
    lensmc.she_lensmc_weight,
    flux_detection_total,
    fluxerr_detection_total,
    b.she_lensmc_fit_flags,
    b.she_lensmc_val_flags,
    b.she_lensmc_fit_class,
    b.she_lensmc_nexp,
    b.she_lensmc_unmasked_fraction,
    b.she_lensmc_rec_flags,
    b.she_lensmc_e1,
    b.she_lensmc_e1_err,
    b.she_lensmc_e2,
    b.she_lensmc_e2_err,
    b.she_lensmc_e_var,
    b.she_lensmc_e1e2_covar,
    b.she_lensmc_weight,
    b.she_lensmc_e1_corrected,
    b.she_lensmc_e1_corrected_err,
    b.she_lensmc_e2_corrected,
    b.she_lensmc_e2_corrected_err,
    b.she_lensmc_e_corrected_var,
    b.she_lensmc_e1e2_corrected_covar,
    b.she_lensmc_weight_cal,
    b.she_lensmc_m11,
    b.she_lensmc_m12,
    b.she_lensmc_m21,
    b.she_lensmc_m22,
    b.she_lensmc_c1,
    b.she_lensmc_c2,
    b.she_lensmc_alpha1,
    b.she_lensmc_alpha2,
    b.she_lensmc_psf_e1,
    b.she_lensmc_psf_e2,
    b.she_lensmc_psf_r2,
    b.she_lensmc_ra,
    b.she_lensmc_ra_err,
    b.she_lensmc_dec,
    b.she_lensmc_dec_err,
    b.she_lensmc_re,
    b.she_lensmc_re_err,
    b.she_lensmc_flux,
    b.she_lensmc_flux_err,
    b.she_lensmc_mag,
    b.she_lensmc_mag_err,
    b.she_lensmc_snr,
    b.she_lensmc_snr_err,
    b.she_lensmc_flux_bulge,
    b.she_lensmc_flux_bulge_err,
    b.she_lensmc_flux_disk,
    b.she_lensmc_flux_disk_err,
    b.she_lensmc_zp,
    b.she_lensmc_bulge_frac,
    b.she_lensmc_bulge_frac_err,
    b.she_lensmc_hlr,
    b.she_lensmc_hlr_err,
    b.she_lensmc_gal_pvalue,
    b.she_lensmc_chi2,
    b.she_lensmc_dof,
    b.she_lensmc_acceptance,
    b.she_lensmc_m1_ical,
    b.she_lensmc_m2_ical,
    b.she_lensmc_shape_noise,
    b.she_metacal_ra,
    b.she_metacal_dec,
    b.she_metacal_e1,
    b.she_metacal_e2,
    b.she_metacal_e_var,
    b.she_metacal_weight,
    b.she_metacal_sn,
    b.she_metacal_r2,
    b.she_metacal_psf_e1,
    b.she_metacal_psf_e2,
    b.she_metacal_psf_r2,
    b.she_metacal_e1_corrected,
    b.she_metacal_e2_corrected,
    b.she_metacal_c1,
    b.she_metacal_c2,
    b.she_metacal_m11,
    b.she_metacal_m12,
    b.she_metacal_m21,
    b.she_metacal_m22,
    b.she_metacal_alpha1,
    b.she_metacal_alpha2,
    b.she_metacal_shape_noise
FROM euclid_tr1_a_v1 AS a
LEFT JOIN euclid_tr1_b_v1_1 AS b
    ON a.object_id = b.object_id
LEFT JOIN euclid_tr1_c_lensmc AS lensmc
    ON b.object_id = lensmc.object_id
WHERE
    phz_mode_1 >= 0.2
    AND phz_mode_1 < 2.5
    AND phz_flags = 0
    AND det_quality_flag IN (0, 1, 2, 3, 512, 513, 514, 515)
    AND spurious_flag = 0
    AND flux_vis_unif <= 575.44
    AND flux_vis_unif >= 0.57544
    AND eff_cov_flag > 0
    AND vis_det = 1
    AND declination < 0