# contains the configuration parameters of the forward model pipeline
dirs:
  # absolute on Perlmutter
  catalog: /pscratch/sd/a/athomsen/y3/y3-cats
  # relative to the root of this repository
  redshift_distributions: data/redshift_distributions

files:
  # relative to the root of this repository
  pixels: data/DESY3_pixels_v11_fiducial_512.h5
  noise: data/DESY3_noise_v11.h5
  meta_info: data/CosmoGridV1_metainfo.h5
  healpy_data: data/healpy_data
  peak_binning: data/peaks/binning/v11_extended.h5
  metacal_bias: data/metacal_biases_desy3.h5

survey:
  name: DESy3
  metacal:
    map_types:
      input: [ kg, ia, dg, dg ]
      output: [ kg, ia, sn, ds ]
    z_bins: [ metacal1, metacal2, metacal3, metacal4 ]
    # used in the forward model (in galaxies/deg^2, computed in notebooks/config.ipynb to respect masking)
    n_gal: [ 5505.792, 5585.636, 5498.44, 5578.685 ]
    # from Table 1 in https://arxiv.org/pdf/2105.13544
    shear_bias:
      multiplicative:
        mu: [ -0.0063, -0.0198, -0.0241, -0.0369 ]
        sigma: [ 0.0091, 0.0078, 0.0076, 0.0076 ]
    # pivot redshift from https://arxiv.org/pdf/2105.13543
    z0: 0.62
    # used to build the observation like eq. (10) in https://arxiv.org/pdf/2403.02314 and shape noise file
    # from Table 1 in https://arxiv.org/pdf/2105.13543
    R_gamma: [ 0.7636, 0.7182, 0.6887, 0.6154 ]
    R_s: [ 0.0046, 0.0083, 0.0126, 0.0145 ]
  maglim:
    map_types:
      input: [ dg ]
      output: [ dg ]
    z_bins: [ maglim1, maglim2, maglim3, maglim4 ]
    # used in the forward model (in galaxies/deg^2, computed in notebooks/config.ipynb to respect masking)
    n_gal: [ 492.807, 351.951, 358.012, 477.993 ]
    # used to build the observation, from Table 1 in https://arxiv.org/pdf/2105.13546
    z_lims: [ [ 0.2, 0.4 ], [ 0.4, 0.55 ], [ 0.55, 0.70 ], [ 0.70, 0.85 ] ]
  # from Table 1 in https://arxiv.org/pdf/2105.13543
  Aeff: 4143

analysis:
  n_side: 512
  n_pix: 3145728
  # minimal n_side_for the networks, determines the padding of the data vectors
  n_side_down: 16
  # number of cut outs from the full sky
  n_patches: 4
  # the six cosmological parameters of the CosmoGrid have to be listed first
  params:
    # same ordering as in the CosmoGrid
    cosmo: [ Om, s8, Ob, H0, ns, w0 ]
    bary: [ bary_Mc, bary_nu ]
    # NLA model + first term of TATT (cross term)
    ia:
      nla: [ Aia, n_Aia ]
      tatt: [ bta ]
    # galaxy biasing
    bg:
      linear: [ bg1, bg2, bg3, bg4 ]
      quadratic: [ bg1_q, bg2_q, bg3_q, bg4_q ]
      stochasticity: [ rg ]
    sc: [ bsc ]
  footprint:
    # the original DES footprint is first rotated around the y- and then the z-axis to enable the cut-outs
    rotation:
      y_rad: -0.125
      z_rad: -1.22
  # see scale_cuts.ipynb. All angles are in arcmin. These are the scale cuts that are baked into the .tfrecords.
  # The angle -> ell conversion is done in the "naive" way in 6.2 of https://academic.oup.com/mnras/article/505/4/5714/6296446
  scale_cuts:
    hard_cut: True
    lensing:
      # from 6.1 in https://arxiv.org/pdf/2110.10135
      l_min: [ 30, 30, 30, 30 ]
      # healpy default of 3 * n_side - 1, since smoothing is done on the fly
      l_max: Null
      theta_fwhm: Null
    clustering:
      # from 6.1 in https://arxiv.org/pdf/2110.10135
      l_min: [ 30, 30, 30, 30 ]
      # healpy default of 3 * n_side - 1, since smoothing is done on the fly
      l_max: Null
      theta_fwhm: Null
  modelling:
    baryonified: True
    store_cross_maps: False
    # degrade the maps to Gaussian Random Fields for testing and comparison to the power spectra
    degrade_to_grf: False
    lensing:
      store: True
      source_clustering: prior
      # whether to include the TATT cross-term on top of NLA
      extended_nla: True
      nla:
        truncate_nz: True
        z_min_quantile: 0.05
        z_max_quantile: 0.95
    clustering:
      store: False
      power_law_biasing: False
      per_bin_biasing: True
      # in addition to linear biasing
      quadratic_biasing: False
      # whether to include a stochasticity in the galaxy biasing. This scales the [-pi, pi] interval from which the
      # random phases with which the alm coefficients are multiplied are drawn. Set to Null to discard.
      stochasticity: False
      # whether to include the survey systematics maps from https://arxiv.org/pdf/2105.13540 in the forward model.
      maglim_survey_systematics_map: False
  normalization:
    # approximate per tomo bin standard deviation of the kg + ia + sn maps at the fiducial cosmology
    lensing: [ 0.0086, 0.0137, 0.0174, 0.0229 ]
    clustering: [ 1, 1, 1, 1 ]
  power_spectra:
    l_min: 30
    l_max: 1500
    n_bins: 33
  grid:
    # CosmoGrid
    n_cosmos: 2500
    n_perms_per_cosmo: 2
    n_noise_per_signal: 2
    priors:
      # from Table 1 in https://arxiv.org/pdf/2201.07771
      Om: [ 0.1, 0.5 ]
      s8: [ 0.4, 1.4 ]
      S8: [ 0.23094010767585035, 1.8073922282301278 ]
      H0: [ 64, 82 ]
      Ob: [ 0.03, 0.06 ]
      ns: [ 0.87, 1.07 ]
      w0: [ -2, -0.333 ]
      # baryons
      bary_Mc: [ 12.0, 15.0 ]
      bary_nu: [ -2, 2.0 ]
      # intrinsic alignment
      Aia: [ -3, 3.0 ]
      n_Aia: [ -4, 6.0 ]
      bta: [ 0.0, 2.0 ]
      # galaxy clustering
      bg1: [ 0.8, 3.0 ]
      bg2: [ 0.8, 3.0 ]
      bg3: [ 0.8, 3.0 ]
      bg4: [ 0.8, 3.0 ]
      rg: [ 0.6, 1.0 ]
      bsc: [ 0.5, 1.5 ]
      Om_s8_border_points:
        [
          [ 0.1, 1.4 ],
          [ 0.2, 1.4 ],
          [ 0.5, 0.65 ],
          [ 0.5, 0.4 ],
          [ 0.3, 0.4 ],
          [ 0.1, 0.9 ],
        ]
  fiducial:
    # CosmoGrid
    n_cosmos: 17 # 1 + 2 * n_perts
    n_perms_per_cosmo: 1000
    n_noise_per_signal: 10
    # from Table 1 in https://arxiv.org/pdf/2201.07771
    Om: 0.26
    s8: 0.84
    S8: 0.7819974424510607
    H0: 67.36
    Ob: 0.0493
    ns: 0.9649
    w0: -1
    # baryons
    bary_Mc: 13.82
    bary_nu: 0.0
    # intrinsic alignment
    Aia: 0.5
    n_Aia: 1.5
    bta: 0.0
    # galaxy clustering (corresponds to bg=1.5, n_bg=0.5)
    bg1: 1.3433586
    bg2: 1.4218498
    bg3: 1.4996815
    bg4: 1.5668583
    rg: 0.8
    perturbations:
      Om: 0.01
      s8: 0.015
      H0: 2.0
      Ob: 0.001
      ns: 0.02
      w0: 0.05
      bary_Mc: 0.1
      bary_nu: 0.1
      Aia: 0.1
      n_Aia: 0.2
      bg1: 0.1
      bg2: 0.1
      bg3: 0.1
      bg4: 0.1
